<?php
require_once 'template/header.phtml';
?>
<div class="split left">
    <div class="centered">
        <h2>Admin Panel</h2>
        <a class="button" href="../admin.php" id="adminbtn" style="margin-left: -80px">
    <span >
        Admin
    </span>
        </a>
    </div>
</div>

<div class="split right">
    <div class="centered">
        <h2>Setup Page</h2>
        <a class="button" href="../step1.php" style="margin-top: -140px; width: 200px; right: 200px; margin-right: -220px">
    <span style="width: 200px">
        Setup
    </span>
        </a>
    </div>
</div>
